name: GitHub Pages

on:
  push:
    branches:
      - hexo

  pull_request:
    branches:
      - hexo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          
      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: algolia
        env:
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
        run: pnpm run algolia

      # submit_url
      - name: submit_url
        env:
          BAIDU_TOKEN: ${{ secrets.BAIDU_TOKEN }}
          BING_TOKEN: ${{ secrets.BING_TOKEN }}
        run: |
          echo -E '${{ secrets.GOOGLE_TOKEN }}' > google_key.json
          pnpm run deploy

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
